from .library import (
    ALL_SCENARIOS,
    FOUR_DAY_WORK_WEEK,
    AI_REGULATION,
    SOCIAL_MEDIA_AGE_LIMITS,
    UNIVERSAL_BASIC_INCOME,
    CRIMINAL_SENTENCING_REFORM,
    CLIMATE_CARBON_TAX,
)

__all__ = [
    "ALL_SCENARIOS",
    "FOUR_DAY_WORK_WEEK",
    "AI_REGULATION",
    "SOCIAL_MEDIA_AGE_LIMITS",
    "UNIVERSAL_BASIC_INCOME",
    "CRIMINAL_SENTENCING_REFORM",
    "CLIMATE_CARBON_TAX",
]
